pipeline:
  tests:
    image: python:${PYTHON_VERSION}
    commands:
     - pip install -r requirements.txt  -r requirements-test.txt
     - flake8 --version
     - flake8
  discord:
    image: appleboy/drone-discord
    secrets: [ discord_webhook_id, discord_webhook_token ]
matrix:
  PYTHON_VERSION:
    - 3.6
